//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BozYapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contact
    {
        public int Contact_ID { get; set; }
        public string Google { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
    }
}
