//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BozYapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Images
    {
        public int Image_ID { get; set; }
        public string Image { get; set; }
        public string Image_Title { get; set; }
        public string Image_Text { get; set; }
    }
}
